### ISSUE TITLE
Determine the best way to lint source files

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-error-reporting#102]
Currently `npm run lint` only lints Javascript files.  However, only the `samples` directory contains Javascript code.  The rest of the code is in TypeScript.

Determine the best approach for linting all of the code in this repo.

**Comment by JustinBeckwith** [comment]
This is already fixed!  `npm run lint` is running `eslint` and `gts check`:
https://github.com/googleapis/nodejs-error-reporting/blob/master/package.json#L36
