### ISSUE TITLE
API link in document is a 404

### ISSUE THREAD

**Issue by AndrewMorsillo** [googleapis/nodejs-error-reporting#111]
The link in the documentation for the API does not work, returns 404. https://cloud.google.com/nodejs/docs/reference/error-reporting/latest/

**Comment by DominicKramer** [comment]
Thank you for letting us know about this.  I will look into this and will let you know of updates on this thread.  Thanks.

**Comment by DominicKramer** [comment]
@jmdobry Do you have any updates on this?

**Comment by ofrobots** [comment]
@JustinBeckwith any ideas how to proceed with this one?

**Comment by JustinBeckwith** [comment]
So we have 2 options here.  One is we go make the changes needed to publish the ref docs on cloud.google.com, and publish there.  Alternatively - we could wait out the `googleapis.dev` thingy, and just plan to go straight to there.  I would prefer the latter.  @kinwa91 what are your thoughts?

**Comment by DominicKramer** [comment]
@jkwlui Friendly ping.

**Comment by ofrobots** [comment]
@jkwlui any update on this?

**Comment by JustinBeckwith** [comment]
Yeah, this one is on me for now.  We are actively working on launching the new docs site where this will live.  It's on the books for Q2, but nothing is imminent.
