### ISSUE TITLE
ERROR:@google/cloud-errors prints to stdout instead of stderr

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-error-reporting#12]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2432

<a href="/kilianc"><img src="https://avatars2.githubusercontent.com/u/385716?s=88&v=4" height=44 width=44 align=left></a><a href="/kilianc">@&shy;kilianc</a><br>July 4, 2017 5:37 AM

```
ERROR:@google/cloud-errors: Encountered an error while attempting to transmit an error to the Stackdriver Error Reporting API. ApiError: User not authorized.
```

I didn't catch this for a long time because it is being printed to stdout instead of stderr.

**Comment by stephenplusplus** [comment]
<a href="/DominicKramer"><img src="https://avatars2.githubusercontent.com/u/14253877?s=88&v=4" height=44 width=44 align=left></a>__<a href="/DominicKramer">@&shy;DominicKramer</a>__<br>July 7, 2017 8:33 PM

It appears that the `log-driver` module that we use for outputting messages always uses `console.log` to output messages.

To address your issue, I've created a `log-driver` PR (https://github.com/cainus/logdriver/pull/6) to add support for specifying a log level at which `console.error` will be used instead of `console.log` for outputting messages, and I'm waiting for feedback from the maintainer of the `log-driver` module.

**Comment by stephenplusplus** [comment]
<a href="/kilianc"><img src="https://avatars2.githubusercontent.com/u/385716?s=88&v=4" height=44 width=44 align=left></a>__<a href="/kilianc">@&shy;kilianc</a>__<br>July 7, 2017 9:52 PM

@DominicKramer that's funny, the headline of the repo is `node logger that only logs to stdout` 🤣

**Comment by stephenplusplus** [comment]
<a href="/DominicKramer"><img src="https://avatars2.githubusercontent.com/u/14253877?s=88&v=4" height=44 width=44 align=left></a>__<a href="/DominicKramer">@&shy;DominicKramer</a>__<br>July 7, 2017 10:09 PM

Since the change is small, I thought I would just suggest it to see what the maintainers of `log-driver` thought.

**Comment by stephenplusplus** [comment]
<a href="/DominicKramer"><img src="https://avatars2.githubusercontent.com/u/14253877?s=88&v=4" height=44 width=44 align=left></a>__<a href="/DominicKramer">@&shy;DominicKramer</a>__<br>July 12, 2017 10:14 PM

@stephenplusplus The `log-driver` module only outputs to standard out.  A logdriver PR [#6](cainus/logdriver#6) was not accepted since the path is to keep that module using only standard out.  What is your perspective on addressing the fact that errors are not printed to standard error?

**Comment by stephenplusplus** [comment]
###### _July 12, 2017 10:23 PM_

My instincts say they should print to `stderr`, but I'd defer to what you and @ofrobots think / have seen in the wild.

**Comment by stephenplusplus** [comment]
<a href="/ofrobots"><img src="https://avatars2.githubusercontent.com/u/79017?s=88&v=4" height=44 width=44 align=left></a>__<a href="/ofrobots">@&shy;ofrobots</a>__<br>July 13, 2017 12:11 AM

Agree with printing to `stderr` – that is more reasonable for libraries. Perhaps we can switch to a different logger, e.g. [npmlog](https://npm.im/npmlog), etc.

**Comment by ofrobots** [comment]
`npmlog` is probably not a good replacement. It is a logger designed for applications rather than libraries. There is single logger instance exported by the module. Mutating the config mutates the entire application globally.

**Comment by ofrobots** [comment]
Switching over to [console-log-level](https://npm.im/console-log-level) over at the Debug agent: https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/479. Will bring that over here once that lands.

**Comment by ofrobots** [comment]
Based on in-person discussion, here it might be better to use `process.emitWarning` instead of a logger. Debug and Trace are 'agents' where as this is just a library.

**Comment by ofrobots** [comment]
I ended up using `console-log-level` as there was a fair amount of logging in place that didn't exactly match the `process.emitWarning` use-cases. I didn't want to change behavior.
