### ISSUE TITLE
nightly system tests failure

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-error-reporting#121]
I noticed a new system tests failure

https://circleci.com/gh/googleapis/nodejs-error-reporting/2704

1) should install and work with code that uses koa

Could you please take a look? 
Thanks!

**Comment by ofrobots** [comment]
It seems that the system tests have not passed recently: https://circleci.com/gh/googleapis/nodejs-error-reporting?page=1 This is blocking the release process.

**Comment by ofrobots** [comment]
Fixed by #162: https://circleci.com/workflow-run/368e7ce4-79d8-437f-abe2-0ed213d4cff8
