### ISSUE TITLE
enabled flag not working

### ISSUE THREAD

**Issue by majelbstoat** [googleapis/nodejs-error-reporting#127]
The google-cloud/trace-agent has a handy feature that lets you pass `enabled` as a flag to the instantiation for whether tracing is enabled or not. It would be great to have a similar feature for error reporting.

I only want to run error reporting in one world - production, and not in dev. This means I currently have to do:

```js
const exp = express()
   .use()
   .use()
if (!dev) {
  errors = new ErrorReporting({})
  exp.use(errors.express)
}
const server = exp.listen()
```

Not the end of the world, but it would be much cleaner to just do:

```js
errors = new ErrorReporting({
  enabled: !dev
})

const server = express()
  .use()
  .use()
  .use(errors.express)
  .listen()
```

Which isn't currently possible as `errors` is undefined in some circumstances. I could of course just unconditionally enable it, without ignoreEnv and without NODE_ENV=production, but then I get warnings in dev.

**Comment by DominicKramer** [comment]
The error reporting library is designed so that errors are only reported if `NODE_ENV=production` or the `ignoreEnvironmentCheck` configuration option is set to `true` so that errors are not reported outside of production unless explicitly enabled.

Does that process not match your use case, or are you seeing errors reported with `NODE_ENV` not set to `production` and `ignoreEnvironmentCheck = false`?  If it is the former, then we can discuss your use case in more detail.  If it is the latter, then this looks like a bug.

Thanks

**Comment by majelbstoat** [comment]
In dev, even with `ignoreEnvironmentCheck = false`, I get the following warnings:

```
ERROR:@google-cloud/error-reporting: Unable to find credential information on instance. This library will be unable to communicate with the Stackdriver API to save errors.  Message: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

It would be my expectation that that warning not show if reporting is not enabled.

**Comment by DominicKramer** [comment]
Yes, that looks like a bug.  Thank you for letting us know about it.  As we investigate it, we'll update this thread.  Thanks.

**Comment by DominicKramer** [comment]
I have PR #295 open that addresses this issue.  If you have any feedback on the approach, please let me know.  Thanks.

**Comment by DominicKramer** [comment]
Version `0.6.0` has been released that contains the `reportMode` configuration option that allows the library to be disabled.  From PR #295:

The `ignoreEnvironmentCheck` configuration option is now
deprecated, and the `reportMode` option should be used
instead.

In particular, the `reportMode` can have one of three values:
* 'production' (default)
   - Only report errors if NODE_ENV is set to "production".:
* 'always'
   - Always report errors regardless of the value of NODE_ENV.
* 'never'
   - Never report errors regardless of the value of NODE_ENV.
