### ISSUE TITLE
Error Reporting could send reported errors to console when in dev mode

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-error-reporting#15]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2754

<a href="/steren"><img src="https://avatars2.githubusercontent.com/u/360895?s=88&v=4" height=44 width=44 align=left></a><a href="/steren">@&shy;steren</a><br>November 22, 2017 6:40 AM

Today, when using the Error Reporting module in development, a warning is printed: 

WARN:@google-cloud/error-reporting: Stackdriver error reporting client has not been configured to send errors, please check the NODE_ENV environment variable and make sure it is set to "production" or the ignoreEnvironmentCheck property is set to true in the runtime configuration object

This is very good. However, when an error is reported, it is swallowed.

Suggestion: when NODE_ENV is not set to "production", the module could simply print the reported errors to console.log().

This would allow testing that error reporting is properly setup while developing.

**Comment by gaastonsr** [comment]
By the way, I think besides choosing if printing to stderr or not the user should also be able to choose if errors should be sent to Stackdriver or not. When developing locally most users won't want development errors to be sent to Stackdriver.

Also, I think this should be implemented with a flag since users might want `staging` or `stage` to work as production too, it's the user responsibility the set the right flags for the different environments the users might have.

**Comment by DominicKramer** [comment]
@gaastonsr Thanks for the feedback.

Version `0.6.0` has just been released that contains the `reportMode` configuration option that allows one to more easily configure when errors are sent to Stackdriver.

From PR #295:

The `ignoreEnvironmentCheck` configuration option is now
deprecated, and the `reportMode` option should be used
instead.

In particular, the `reportMode` can have one of three values:
* 'production' (default)
   - Only report errors if NODE_ENV is set to "production".:
* 'always'
   - Always report errors regardless of the value of NODE_ENV.
* 'never'
   - Never report errors regardless of the value of NODE_ENV.

Does this configuration option meet your needs?

**Comment by gaastonsr** [comment]
Yup, that works. Users can set `reportMode: 'always'` if they want `staging` to be sent to Stackdriver too.

By the way, I just found out that `@google-cloud/logging-winston` also logs to the reporting API if the appropriate fields are filled when logging the errors so I'm using that instead.

**Comment by DominicKramer** [comment]
Awesome.
