### ISSUE TITLE
Imports incompatible with TypeScript

### ISSUE THREAD

**Issue by lpellegr** [googleapis/nodejs-error-reporting#155]
I am using this library with Firebase functions written in TypeScript. Since I upgraded to version `0.5.0` I am getting the following error from tslint:

> node_modules/@google-cloud/error-reporting/node_modules/@google-cloud/common/build/src/service-object.d.ts:18:8 - error TS1192: Module '"/home/lpellegr/X/functions/node_modules/@types/request/index"' has no default export.
> 
> 18 import r from 'request';
>           ~
> 
> 
> node_modules/@google-cloud/error-reporting/node_modules/@google-cloud/common/build/src/service.d.ts:17:8 - error TS1192: Module '"/home/lpellegr/X/functions/node_modules/@types/request/index"' has no default export.
> 
> 17 import r from 'request';
>           ~
> 
> 
> node_modules/@google-cloud/error-reporting/node_modules/@google-cloud/common/build/src/util.d.ts:20:8 - error TS1192: Module '"/home/lpellegr/X/functions/node_modules/@types/duplexify/index"' has no default export.
> 
> 20 import duplexify from 'duplexify';
>           ~~~~~~~~~
> 
> 
> node_modules/@google-cloud/error-reporting/node_modules/@google-cloud/common/build/src/util.d.ts:23:8 - error TS1192: Module '"/home/lpellegr/X/functions/node_modules/@types/request/index"' has no default export.
> 
> 23 import r from 'request'; 

There were no issues with version `0.4.0`. TypeScript `2.9.2` is used.

**Comment by ofrobots** [comment]
@lpellegr thanks for the report. I think this problem is due to one of our dependencies (`@google-cloud/common`) using the new `allowSyntheticImports` feature in TypeScript which leaks through to the users 😰.

I think this has already been fixed upstream, and picking up a new release of the library will fix the problem.

I *believe* this will go away a new release of `@google-cloud/logging` is done and we pick that up here.

**Comment by ofrobots** [comment]
Blocked on https://github.com/googleapis/nodejs-logging/pull/149.

**Comment by ofrobots** [comment]
Fix over in #158.

I was confusing this issue with another one in `@google-cloud/logging-winston`. This did not depend on googleapis/nodejs-logging#149.

**Comment by ofrobots** [comment]
@lpellegr 0.5.1 has been release which should no longer have this issue. Please give this a shot and re-open or comment here if you're still running into issues.
