### ISSUE TITLE
Allow adding custom examples in the README

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-error-reporting#190]
Nodejs-repo-tools issue [#123](https://github.com/GoogleCloudPlatform/nodejs-repo-tools/issues/123) needs to land so that we can add custom examples in the README file.

**Comment by JustinBeckwith** [comment]
nodejs-repo-tools is no longer the path forward here.  @crwilcox documented a templating feature in synthtool that we should instead :)

**Comment by crwilcox** [comment]
@DominicKramer , is the edit needed to include a sample? The previous tooling supported that. I am curious if you can provide details on what makes this case special?

**Comment by DominicKramer** [comment]
@crwilcox I need to include additional documentation and samples to the readme.  Do you have an example of what the `synthool.py` script would need to be to have synthool generate a Readme similar to the default Readme but with additional samples included?  Thanks.

**Comment by JustinBeckwith** [comment]
For posterity, this is blocked right now by https://github.com/googleapis/google-cloud-node/issues/2868.

**Comment by DominicKramer** [comment]
I have PR #313 open that updates the README.  I think it would be good to have the README updated the way I have it (at least in the short term) so that users have access to additional documentation.  Then we can make a tracking bug to have the README use synthtool for the long term.  The updated README will also help guide the type of functionality I need in synthtool too, which I think is helpful.
