### ISSUE TITLE
Hapi: correctly extract url from request object

### ISSUE THREAD

**Issue by AdriVanHoudt** [googleapis/nodejs-error-reporting#196]
If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS: Mac/Linux
  - Node.js version: 8.11.4
  - npm version: 6.4.0
  - @google-cloud/error-reporting version: 0.5.1
  - hapi version: 16.x (<- probably the most important one :D)

#### Steps to reproduce

  1. Throw in request handler
  2. Error logged in cloud console is missing an url
	* ![image](https://user-images.githubusercontent.com/2361826/44405821-77c77480-a55a-11e8-8f87-7fe6858c1c39.png)

This is due to 
https://github.com/googleapis/nodejs-error-reporting/blob/259f04d6eb7c9f5636141c1a7d3b5ff0d61ce028/src/request-extractors/hapi.ts#L90
`req.url` can be an URL object. I would suggest to fallback to `req.path` or `req.url.path`.
If that sounds ok I can do a PR if you'd like

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by DominicKramer** [comment]
Thank you for opening this issue.  On initial investigation, I agree that using `req.url.pathname` should be used if `req.url` is a URL object.  Feel free to open a PR if you want to, but don't feel like you need to.  We can take care of this too.  Thanks.

**Comment by AdriVanHoudt** [comment]
I don't know typescript that well so not sure what `as {} as string` is doing so not sure what the quick fallback fix for this would be, thanks for picking this up!
