### ISSUE TITLE
Fix the system tests

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-error-reporting#213]
The system tests on this repo are currently broken on master.  It looks like this library expected some special environment variables to be set.  We should probably just the tests to be consistent with all of the other repos. 
https://circleci.com/gh/googleapis/nodejs-error-reporting/5200

**Comment by kinwa91** [comment]
We fixed the system-test keys - however @DominicKramer mentioned that we have a number of flaky system test that are causing it to fail sometimes.

**Comment by DominicKramer** [comment]
I'm actively investigating why the tests are failing, and I'll let you know if I have any blockers.

**Comment by DominicKramer** [comment]
I thought PR #216 would address this issue.  However, there is still flakiness in the tests that I am still investigating.
