### ISSUE TITLE
Re-enable the "should not issue a warning if it can communicate with the API" test

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-error-reporting#221]
This test was skipped because when migrating to `--throw-deprecation`, it was discovered that it never really worked.  This should be fixed and turned back on.

**Comment by DominicKramer** [comment]
Thanks for letting me know :)

**Comment by ofrobots** [comment]
AFAICT the test is still active: https://github.com/googleapis/nodejs-error-reporting/blob/2fbbd38006db495129a8e6961ab2f2b2a0b105e2/test/unit/google-apis/auth-client.ts#L145. @JustinBeckwith do you have any more context?

**Comment by JustinBeckwith** [comment]
I.... honestly don't remember.
