### ISSUE TITLE
Need to update unit tests to make coverage reach 100%

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-error-reporting#24]
We try to keep unit test coverage at 100% which is not the case for this library.

**Comment by JustinBeckwith** [comment]
I don't think this is a useful goal:
https://labs.ig.com/code-coverage-100-percent-tragedy

If we find areas that aren't well tested - we should test them!  But I don't think 100% coverage for the sake of 100% coverage is on the horizon anytime soon :)
