### ISSUE TITLE
Move samples to this repo

### ISSUE THREAD

**Issue by fhinkel** [googleapis/nodejs-error-reporting#251]
Hi there, our docs-samples repo still have some [error-reporting](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/error-reporting) samples. For Node.js, all samples live with their client library if they have one. Can you move the samples over please. Thanks! cc @ofrobots

**Comment by fhinkel** [comment]
Did this already happen? Our docs link to the samples here.

**Comment by DominicKramer** [comment]
Not yet.

**Comment by fhinkel** [comment]
I think they were moved 8 months ago 😉

**Comment by JCIV-SE** [comment]
Should this issue be closed?

**Comment by DominicKramer** [comment]
Closing since this repo already contains samples.
