### ISSUE TITLE
koa2 fix not published to npm

### ISSUE THREAD

**Issue by codyzu** [googleapis/nodejs-error-reporting#256]
#### Environment details

  - OS: Ubuntu Linux 18.10
  - Node.js version: 10.13.0
  - npm version: 6.4.1
  - `@google-cloud/error-reporting` version: 0.2.3

#### Steps to reproduce

  1. Create koa webserver
  2. Use latest version published on npm 0.5.1
  3. No errors reporting and middleware stack broken

It looks like this has been fixed in the code with the koa2 interface. When will this be released and published to npm?

**Comment by DominicKramer** [comment]
Thank you for opening this issue.  I am currently working on a problem in the system tests that is blocking a release.  When I have that resolved I will be able to make a release.  I will keep this thread updated with info as it becomes available.  Thanks.

**Comment by DominicKramer** [comment]
Version 0.5.2 has been released that contains the fix.
