### ISSUE TITLE
Determine if Restify 8 is supported

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-error-reporting#319]
Restify 8 is available and we need to ensure the error reporting library can be used with it.

**Comment by ofrobots** [comment]
Have users actually asked for this?

**Comment by DominicKramer** [comment]
This isn't something a customer has asked for.  It is just that Restify 8 has been released.  What is needed then is:

1. Determine if Restify 8 is supported.
2. If not, determine if it is something we want supported.  If yes, support it.  If not, ensure the error reporting documentation makes that clear.

From the Restify changelog I suspect Restify 8 should just work, and so I suspect the answer to (1) is yes, making (2) irrelevant.

**Comment by DominicKramer** [comment]
I have confirmed that Restify 8 works with the error reporting library.  PR #324 adds Restify 8 tests to the install tests.
