### ISSUE TITLE
Use google-auth-library 1.0

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-error-reporting#33]
`google-auth-library` version 1.0 includes type definitions.  When the translation of the error reporting code to Typescript has completed, bring in `google-auth-library` >=1.0 to remove manually written type definitions in the error-reporting code.

**Comment by ofrobots** [comment]
It is not a local dependency however. Looking at the dep chain, I think `google-auto-auth` needs to upgrade (at least).

**Comment by JustinBeckwith** [comment]
Since we upgraded to the latest `@google-cloud/common`, this is fixed :)

**Comment by DominicKramer** [comment]
Awesome
