### ISSUE TITLE
koa2 interface not awaiting next middleware

### ISSUE THREAD

**Issue by codyzu** [googleapis/nodejs-error-reporting#335]
https://github.com/googleapis/nodejs-error-reporting/blob/4bd26cdebfc57d02d4c6a548af760efcff2bc2bf/src/interfaces/koa2.ts#L57

`next` is function in koa. This should be `await next()`, awaiting the response from the next function (i.e. the next middleware in the stack).

I would go as far to say there must be something missing in the tests this hasn't been noticed before :-(

#### Environment details

  - OS: linux
  - Node.js version: 10.15.1
  - npm version: 6.4.1
  - `@google-cloud/error-reporting` version: 0.6.1

#### Steps to reproduce

  1. Use koa2 interface in middleware stack
  1. Call api and watch 404s get returned....

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  I have a PR at #336 that addresses this.  Our tests verify that the interface of the plugin we export matches that what is expected from the framework.  The type for `next` should not have been `{}` but should have been something more precise (at least `Function`).

**Comment by codyzu** [comment]
@DominicKramer thanks for your quick fix for this... however, you fixed the `koa` interface _not_ the `koa2` interface (as described in the `0.6.2` release changelog). Can you fix the `koa2` interface and roll a new release?

Thanks again for your fast work!

**Comment by DominicKramer** [comment]
Sorry about that.  I have PR #339 to fix the Koa2 interface too.

**Comment by DominicKramer** [comment]
Version 0.6.3 is out.  I'm able to use it to with Koa2, and errors correctly show up in the Error Reporting Console.  If you are still having problems, let us know.  Thanks.

**Comment by codyzu** [comment]
Super big thank you for your very reactive fix! I’ll test this out tomorrow. Thanks again!

**Comment by DominicKramer** [comment]
Glad to be of help.
