### ISSUE TITLE
Move samples from README to samples directory

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-error-reporting#337]
Move the samples from the README to the samples directory and update the samples tests to validate each sample.

**Comment by housemex408** [comment]
@DominicKramer is this issue blocked?  looks like it was merged, does this PR need to be deleted?

**Comment by DominicKramer** [comment]
No this is still something I am working on.  Then I can close it.

**Comment by DominicKramer** [comment]
Closing since I don't think this is really needed.
