### ISSUE TITLE
Library should automatically pick up service and revision name in Knative environments

### ISSUE THREAD

**Issue by steren** [googleapis/nodejs-error-reporting#370]
When running on Cloud Run, or Cloud Run on GKE or any Knative install, the library should pick up the `K_SERVICE` env var and associate it to the "service" and the `K_REVISION` env var and associate it to "version".

These env vars are part of the Knative runtime contract, see [here](https://github.com/knative/serving/blob/master/docs/runtime-contract.md#process)

cc @ofrobots

**Comment by DominicKramer** [comment]
Thanks for letting us know about this.
