### ISSUE TITLE
Only try to authenticate if reporting is enabled.

### ISSUE THREAD

**Issue by rhodgkins** [googleapis/nodejs-error-reporting#550]
When running this package locally with `reportMode: 'never'` which [prevents any reporting](https://github.com/googleapis/nodejs-error-reporting/blob/419a5e176fb1c0ecfcf811457c6e5ea46a048506/src/google-apis/auth-client.ts#L176) but we still get an console message about not being able to find credential information because when creating the error reporting client [authentication is still attempted](https://github.com/googleapis/nodejs-error-reporting/blob/419a5e176fb1c0ecfcf811457c6e5ea46a048506/src/google-apis/auth-client.ts#L114).

Would it be possible for a similar check be put in before attempting this (both API key and obtaining an access token)?

**Comment by nicoleczhu** [comment]
This is a really good suggestion & I dont see tradeoffs off the bat. We should add it to this library & short-circuit auth in this case.

**Comment by spaghettiguru** [comment]
any progress with this?

**Comment by filipecatraia** [comment]
Hey APIs team, between this and #460 it's been quite a long time :)
