### ISSUE TITLE
Request exceptions are reported with statusCode=200

### ISSUE THREAD

**Issue by cakoose** [googleapis/nodejs-error-reporting#583]
I have a Node.js Cloud Run service.  I'm using Express for routing and set up "@google-cloud/error-reporting" as recommended, roughly:

```
const app = express()

...

app.use(errors.express);
```

My issue: in the GCP "Logs Explorer" console page, request exceptions are being reported with statusCode=200.

I think this _might_ be because this library gets the error code from `res.statusCode` ((code)[https://github.com/googleapis/nodejs-error-reporting/blob/0e09c847e8effb7a240d536a3fec74b2b485912f/src/request-extractors/express.ts#L68])), which maybe defaults to 200 until it's explicitly set?

Maybe this library's Express error handler shouldn't set the status code, since it's not clear what `res.statusCode` means when there's an error?

#### Environment details

  - OS: docker.io/library/node:14.16.1-buster-slim
  - Node.js version: 14.16.1
  - npm version: Yarn 3.0.0-rc2
  - `@google-cloud/error-reporting` version: 2.0.2 (from my "yarn.lock")

**Comment by minherz** [comment]
Hi @cakoose, i apologies for the delayed response. I had looked into the issue and can confirm that you correctly described the current behavior of the library. It is a designed behavior. The library provides an interface to report an error event and record the event to a log. Such event is not necessary based on the Http request status. With that, the reporting objects is populate with maximum metadata that is available/provided so it will grant to [Error Reporting](https://cloud.google.com/error-reporting/docs/) service.
I hope this answers your question.
