### ISSUE TITLE
Export `ErrorMessage` from index.ts?

### ISSUE THREAD

**Issue by cakoose** [googleapis/nodejs-error-reporting#584]
I'm using the "manual error reporting" flow.  What's a little strange is that the `ErrorMessage` type (returned from `ErrorReporting.event()` isn't exported from the top-level of the package.

I end up having to import it from a weird spot, e.g.:

```ts
import {ErrorMessage} from '@google-cloud/error-reporting/build/src/classes/error-message';
```

Is there a better way to import this type?

**Comment by nicoleczhu** [comment]
Great point - we should explicitly export it.
