### ISSUE TITLE
Determine the license of base64-js@0.0.2

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-error-reporting#61]
js-green-licenses reports the following:
```
(no license): base64-js@0.0.2
  @google-cloud/error-reporting@0.2.2 -> snyk@1.69.7 -> snyk-nuget-plugin@1.3.9 -> zip@1.2.0 -> bops@0.1.1 -> base64-js@0.0.2
```
Determine if it is ok to use `base64-js@0.0.2`.

**Comment by jinwoo** [comment]
This was only due ot the snyk patches, right? I think we can close this.

**Comment by DominicKramer** [comment]
Yes, that is correct.  When I opened this, I wasn't sure if I wanted to use the Snyk generated PR.  At this point, I think I will manually create a PR.  Thus I'll close this.
