### ISSUE TITLE
Add support for hapi@17.0.0

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-error-reporting#62]
The hapi request handler cannot be used, as is, with hapi@17.0.0.  Update it to support hapi@17.0.0.  However, support for previous versions of hapi should still be maintained.

**Comment by BenCrux** [comment]
I see a branch for this, is this in progress?

**Comment by DominicKramer** [comment]
Yes, I am currently working on this.  I will let you know of any updates.  Thanks.

**Comment by DominicKramer** [comment]
PR #89 adds support for Hapi17.  I plan to have a release out including it as soon as possible.  In the meantime, if you would like to test it out now, you can install from the branch using:
```
npm install https://github.com/DominicKramer/nodejs-error-reporting.git#feat/support-hapi17
```
If you have any issues or comments, please let me know.  Thanks.

**Comment by BenCrux** [comment]
Great - thanks @DominicKramer! How should I track the release status?

**Comment by DominicKramer** [comment]
I hope to have this released soon, and I'll update this thread when the release occurs.  Thanks.

**Comment by DominicKramer** [comment]
Version 0.4.0 has been released that includes support for Hapi 17.  Please let me know if you have any issues.  Thanks.
