### ISSUE TITLE
Generate Typescript declaration files

### ISSUE THREAD

**Issue by moberemk** [googleapis/nodejs-error-reporting#68]
Since this library is already written in Typescript, it'd be great if the actual declaration files were included with the package already [as defined by this package.json property](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package).

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  The next release will include declaration files and will be released after PR #60 has landed (which has tests that verify the declaration files work as expected).  I will update this issue when the next release is out.

**Comment by moberemk** [comment]
Oh awesome, so it does; I tried searching the issues/pulls to see if this'd be addressed already and I didn't catch that PR was intended to address this. Thanks!

**Comment by DominicKramer** [comment]
Version 0.3.2 has been released that includes type definitions.  If you have any problems with the type definitions generated, please let me know.  Thanks.
