### ISSUE TITLE
ERROR:@google-cloud/error-reporting: Unable to find credential information on instance. This library will be unable to communicate with the Google Cloud API to save errors. Message: request to https://www.googleapis.com/oauth2/v4/token failed, reason: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by raphaelarias** [googleapis/nodejs-error-reporting#688]
#### Environment details

  - OS: node:18-alpine (running on Cloud Run)
  - Node.js version: 18
  - `@google-cloud/error-reporting` version: `3.0.1`

#### Steps to reproduce

I've been trying to reproduce in local, but I couldn't. So it makes me believe is due to the Cloud Run enviroment (?).
  1. The Cloud Error API gets called manually before on `response.on('finish')` of Expressjs.
  2. The error is created on Error reporting:
 <img width="1772" alt="image" src="https://user-images.githubusercontent.com/5008166/205518537-515dcc87-1fc1-4be0-ae9b-26827b76466a.png">
  3. Here we can see the a request failing with 504 (failed on purpose for this test), triggering the Error Reporting. Then the timeout and eventually container exiting due to this error.
<img width="1757" alt="image" src="https://user-images.githubusercontent.com/5008166/205518432-7fa40c9d-e9d1-4221-a8c8-bbdbfb293019.png">

I've put a console.log on `process.on('uncaughtException'`, and these are the errors eventually killing the container.
```
ERROR:@google-cloud/error-reporting: Unable to find credential information on instance. This library will be unable to communicate with the Google Cloud API to save errors. Message: request to https://www.googleapis.com/oauth2/v4/token failed, reason: Client network socket disconnected before secure TLS connection was established

4 DEADLINE_EXCEEDED: Deadline exceeded
```

In all my tests, everything always works as expected, but when deployed to Cloud Run, it fails (kinda, it still works, but then it kills the container). I've searched in the documentation for an explanation or specific adjustments needed when using it with Cloud Run, and couldn't find anything.

Thanks!

**Comment by meredithslota** [comment]
A similar error was reported previously in StackOverflow, but it's not clear if it was happening while using Cloud Run or not: https://stackoverflow.com/questions/67411984/errorgoogle-cloud-error-reporting-encountered-an-error-while-attempting-to-tr — the recommended approach was to ensure that the Error Reporting Writer permission was appropriately granted to your service account in the relevant projects. 

Can you validate that the permissions in Cloud Run are correct for this? https://cloud.google.com/error-reporting/docs/iam#errorreporting.writer describes this role.

**Comment by meredithslota** [comment]
I'll note that the documentation here re: Cloud Run setup is a bit sparse and doesn't mention this — https://cloud.google.com/error-reporting/docs/setup/cloud-run — and I've filed an internal issue asking for additional details to be added.

**Comment by losalex** [comment]
Closing this issue for now - please feel free to reactivate if issue still happens. Thanks!
