### ISSUE TITLE
system tests should not fail

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-error-reporting#79]
Since we now have nightly builds running, it's critical that all tests should pass. Could you please take a look at the system tests failure and fix it: https://circleci.com/gh/googleapis/nodejs-error-reporting/1325

Cc: @ofrobots for awareness

**Comment by DominicKramer** [comment]
This is being addressed in PR #74 which should land soon.

**Comment by DominicKramer** [comment]
This has been fixed by PR #74.
