### ISSUE TITLE
Investigate Supporting koa@next

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-error-reporting#8]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2295

<a href="/DominicKramer"><img src="https://avatars2.githubusercontent.com/u/14253877?s=88&v=4" height=44 width=44 align=left></a><a href="/DominicKramer">@&shy;DominicKramer</a><br>May 11, 2017 9:37 PM

The cloud-errors-nodejs repository has PR [#97](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/97) that already contains some preliminary work.

**Comment by mike-marcacci** [comment]
Please note that because typescript compiles the generator down in such that its `.constructor` is `Function` (rather than `GeneratorFunction`), packages like [koa-convert](https://www.npmjs.com/package/koa-convert) aren't able to make this work with koa@2 (which was published in March of 2016).
