### ISSUE TITLE
error-reporting: Add deleteEvents and getEvents module methods

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-error-reporting#9]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2296

<a href="/DominicKramer"><img src="https://avatars2.githubusercontent.com/u/14253877?s=88&v=4" height=44 width=44 align=left></a><a href="/DominicKramer">@&shy;DominicKramer</a><br>May 11, 2017 9:48 PM

The cloud-errors-nodejs repository has PR [#99](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/99) that already contains some preliminary work.

**Comment by DominicKramer** [comment]
These features are not required for the functionality of this library, but could be nice to have.  However, since there doesn't seem to be a strong want or need for this functionality, I am going to close this issue now to allow focusing on other features of higher priority.
