### ISSUE TITLE
Use `repo-tools` directly

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-error-reporting#94]
PR #93 uses `node node_modules/.bin/repo-tools` to invoke `repo-tools` instead of invoking `repo-tools` directly.  This was done because on CircleICI the `repo-tools` file sometimes doesn't have its executable bit set.

Invoke `repo-tools` directly when the underlying executable bit bug is fixed.

**Comment by JustinBeckwith** [comment]
I just dumped repo tools as part of a CircleCI cleanup, and fixed the path issues.
