### ISSUE TITLE
error TS2307: Cannot find module '@google-cloud/error-reporting'

### ISSUE THREAD

**Issue by bnfrnz** [googleapis/nodejs-error-reporting#97]
#### Environment details
  - OS: macOS 10.13.3 (17D102)
  - Node.js version: 6.12.2
  - npm version: 5.6.0
  - error-reporting version: 0.3.0

#### Steps to reproduce
`npm i @google-cloud/error-reporting@latest`
`import { ErrorReporting } from '@google-cloud/error-reporting';`
`const errors = new ErrorReporting();`

I'm getting `error TS2307: Cannot find module '@google-cloud/error-reporting'` using above import via TypeScript as per [Breaking Changes](https://github.com/googleapis/nodejs-error-reporting/releases/tag/v0.3.0). Am I missing something?

I realize this sounds more like a support query than a github issue but when I look at the installed module I can't seem to find where `ErrorReporting` is being declared or exported: [screen shot 2018-03-28 at 15 32 11](https://user-images.githubusercontent.com/26401091/38015085-50a9a7e0-329d-11e8-88a5-d1d742588d04.png)

I must be missing something. Or is this a moduleResolution issue?

My apologies if this is PEBCAK. I just downgraded to @google-cloud/error-reporting@0.2.3 for now and stuff is working fine again.

**Comment by zamiang** [comment]
I believe this is because the 0.3.0 release of '@google-cloud/error-reporting' doesn't include any actual packaged files. According to package.json, there should be a build directory which includes the types and package

```
$ ls node_modules/\@google-cloud/error-reporting/
LICENSE         README.md       node_modules    package.json
```

**Comment by DominicKramer** [comment]
Thank you for opening this issue.  I think I know what the root cause is, and I'll have another release out as soon as possible.

**Comment by DominicKramer** [comment]
Version v0.3.2 should address this issue.  I'm sorry for any inconvenience, and please let me know if you have any other issues.  Thanks.
